---
- name: Check if selinux needed
  command: getenforce
  register: selinux_check
  changed_when: false

- name: Set fact
  set_fact: selinux_status={{ selinux_check.stdout == "Enforcing" or selinux_check.stdout == "Permissive" }} 

- name: Install selinux
  yum: name={{ local_repo_path }}/libselinux-python-2.0.94-5.8.el6.x86_64.rpm
  when: selinux_status
