alter table MTestAgentModule add snmp_id integer generated by default as sequence snmp_id_seq;
update MTestAgentModule set snmp_id = next value for snmp_id_seq;
alter table MTestAgentModule add constraint MTestAgentModule_snmp_id_unique unique (snmp_id);
alter table MTestAgentModule alter column snmp_id set not null;