---
- name: Create Postgres user with ssh keys
  user: name=postgres
        generate_ssh_key=yes
        uid=26
        system=yes
        shell=/bin/bash
        home=/var/lib/pgsql
        comment="PostgreSQL Server"

- name: Get the public key off the machine
  slurp: src="~postgres/.ssh/id_rsa.pub"
  register: sshkey

- name: Install key on remote hosts
  authorized_key: user=postgres key="{{ sshkey.content|b64decode }}"
  delegate_to: "{{ item }}"
  with_items: groups['db']

- name: Setup known hosts file
  template: src=known_hosts.j2 dest=/etc/ssh/ssh_known_hosts mode=0644 owner=root group=root backup=yes

- name: Allow the postgres user to run the init script
  copy: src=sudoers dest=/etc/sudoers.d/postgres owner=root group=root mode=0600 backup=yes
