alter table MResultParameterConfiguration add snmp_id integer generated by default as sequence snmp_id_seq;
update MResultParameterConfiguration set snmp_id = next value for snmp_id_seq;
alter table MResultParameterConfiguration add constraint MResultParameterConfiguration_snmp_id_unique unique (snmp_id);
alter table MResultParameterConfiguration alter column snmp_id set not null;
