create sequence snmp_id_seq start with 1 increment by 1;

alter table MAgentModule add snmp_id integer generated by default as sequence snmp_id_seq;
update MAgentModule set snmp_id = next value for snmp_id_seq;
alter table MAgentModule add constraint MAgentModule_snmp_id_unique unique (snmp_id);
alter table MAgentModule alter column snmp_id set not null;

alter table MMediaAgentModule add snmp_id integer generated by default as sequence snmp_id_seq;
update MMediaAgentModule set snmp_id = next value for snmp_id_seq;
alter table MMediaAgentModule add constraint MMediaAgentModule_snmp_id_unique unique (snmp_id); 
alter table MMediaAgentModule alter column snmp_id set not null;

alter table MAgentTask add snmp_id integer generated by default as sequence snmp_id_seq;
update MAgentTask set snmp_id = next value for snmp_id_seq;
alter table MAgentTask add constraint MAgentTask_snmp_id_unique unique (snmp_id);
alter table MAgentTask alter column snmp_id set not null;

alter table MPolicy add snmp_id integer generated by default as sequence snmp_id_seq;
update MPolicy set snmp_id = next value for snmp_id_seq;
alter table MPolicy add constraint MPolicy_snmp_id_unique unique (snmp_id);
alter table MPolicy alter column snmp_id set not null;

alter table MPolicyTemplate add snmp_id integer generated by default as sequence snmp_id_seq;
update MPolicyTemplate set snmp_id = next value for snmp_id_seq;
alter table MPolicyTemplate add constraint MPolicyTemplate_snmp_id_unique unique (snmp_id);
alter table MPolicyTemplate alter column snmp_id set not null;

alter table MAgent add snmp_id integer generated by default as sequence snmp_id_seq;
update MAgent set snmp_id = next value for snmp_id_seq;
alter table MAgent add constraint MAgent_snmp_id_unique unique (snmp_id);
alter table MAgent alter column snmp_id set not null;