---------------------------------------------------------
--  DDL for Table AGENT
--------------------------------------------------------
DROP TABLE "AGENT_COPY"
;

CREATE TABLE "AGENT_COPY" (
  "ID" NUMBER(10,0), 
  "NAME" VARCHAR2(400), 
  "DISPLAYNAME" VARCHAR2(400), 
  "DESCRIPTION" VARCHAR2(800), 
  "TIMEZONE" VARCHAR2(400),
  "DIVISION_ID" NUMBER(10,0),
  "DELETED" NUMBER(10,0) DEFAULT 0, 
  "CREATION_DATE" DATE, 
  "CREATION_USER" VARCHAR2(60), 
  "MOD_USER" VARCHAR2(60), 
  "MOD_TS" TIMESTAMP (6), 
  "MOD_VERS" NUMBER(10,0), 
  "SELECTED_PROFILE_ID" NUMBER(10,0), 
  "IP_ADDRESS" VARCHAR2(15),
  "GISPOSITION_ID" NUMBER(10,0),
  "LIVEBROADCAST_ID" NUMBER(10,0))
  ;

 Insert into AGENT_COPY (ID,NAME,DISPLAYNAME,DESCRIPTION,TIMEZONE,DIVISION_ID,DELETED,CREATION_DATE,CREATION_USER,MOD_USER,MOD_TS,MOD_VERS,SELECTED_PROFILE_ID,IP_ADDRESS,GISPOSITION_ID, LIVEBROADCAST_ID) values ('221','FirstChannel-NN','"Первый Канал" - Нижний Новгород','Мониторинг объектов вещания Первого канала',null,'1','0',null,null,null,to_timestamp('17.10.12 09:32:29,739352000','DD.MM.RR HH24:MI:SS,FF'),'21',null,'91.228.161.16','4979414', '5177802')
 ;
--Insert into AGENT_COPY (ID,NAME,DISPLAYNAME,DESCRIPTION,TIMEZONE,DIVISION_ID,DELETED,CREATION_DATE,CREATION_USER,MOD_USER,MOD_TS,MOD_VERS,SELECTED_PROFILE_ID,IP_ADDRESS,GISPOSITION_ID, LIVEBROADCAST_ID) values ('241','"Первый Канал" - (резервный)','"Первый Канал" - (резервный)','Мониторинг объектов вещания Первого канала (резервный)',null,'1','241',null,null,null,to_timestamp('19.09.12 10:32:22,667660000','DD.MM.RR HH24:MI:SS,FF'),'3',null,'192.168.115.234', null, null);
--Insert into AGENT_COPY (ID,NAME,DISPLAYNAME,DESCRIPTION,TIMEZONE,DIVISION_ID,DELETED,CREATION_DATE,CREATION_USER,MOD_USER,MOD_TS,MOD_VERS,SELECTED_PROFILE_ID,IP_ADDRESS,GISPOSITION_ID, LIVEBROADCAST_ID) values ('326','"Первый Канал" - Самара','"Первый Канал" - Самара',null,null,'1','0',null,null,null,to_timestamp('29.10.12 14:31:37,372158000','DD.MM.RR HH24:MI:SS,FF'),'1',null,null, null, null);
Insert into AGENT_COPY (ID,NAME,DISPLAYNAME,DESCRIPTION,TIMEZONE,DIVISION_ID,DELETED,CREATION_DATE,CREATION_USER,MOD_USER,MOD_TS,MOD_VERS,SELECTED_PROFILE_ID,IP_ADDRESS,GISPOSITION_ID, LIVEBROADCAST_ID) values ('281','FirstChannel-UFA','"Первый канал"- Уфа',null,null,'1','0',null,null,null,to_timestamp('19.09.12 11:53:15,141577000','DD.MM.RR HH24:MI:SS,FF'),'3',null,'81.30.220.218','4979413', '5177803')
;
Insert into AGENT_COPY (ID,NAME,DISPLAYNAME,DESCRIPTION,TIMEZONE,DIVISION_ID,DELETED,CREATION_DATE,CREATION_USER,MOD_USER,MOD_TS,MOD_VERS,SELECTED_PROFILE_ID,IP_ADDRESS,GISPOSITION_ID, LIVEBROADCAST_ID) values ('285','FirstChannel-KIROV','"Первый канал" - Киров',null,null,'1','0',null,null,null,to_timestamp('20.09.12 07:24:43,162784000','DD.MM.RR HH24:MI:SS,FF'),'1',null,'77.72.137.210','4979408', '5177804')
;
--Insert into AGENT_COPY (ID,NAME,DISPLAYNAME,DESCRIPTION,TIMEZONE,DIVISION_ID,DELETED,CREATION_DATE,CREATION_USER,MOD_USER,MOD_TS,MOD_VERS,SELECTED_PROFILE_ID,IP_ADDRESS,GISPOSITION_ID, LIVEBROADCAST_ID) values ('261','РЧЦ Нижний Новгород','РЧЦ Нижний Новгород','Мониторинг FM вещания Нижний Новгород',null,'1','261',null,null,null,to_timestamp('19.09.12 10:32:22,668155000','DD.MM.RR HH24:MI:SS,FF'),'2',null,'192.168.115.68', null, null);
--Insert into AGENT_COPY (ID,NAME,DISPLAYNAME,DESCRIPTION,TIMEZONE,DIVISION_ID,DELETED,CREATION_DATE,CREATION_USER,MOD_USER,MOD_TS,MOD_VERS,SELECTED_PROFILE_ID,IP_ADDRESS,GISPOSITION_ID, LIVEBROADCAST_ID) values ('301','"Первый Канал" - Нижний Новгород(2)','"Первый Канал" - Нижний Новгород(2)',null,null,'1','0',null,null,null,to_timestamp('25.10.12 13:17:54,965225000','DD.MM.RR HH24:MI:SS,FF'),'2','163','192.168.13.45', 4979415, null);
Insert into AGENT_COPY (ID,NAME,DISPLAYNAME,DESCRIPTION,TIMEZONE,DIVISION_ID,DELETED,CREATION_DATE,CREATION_USER,MOD_USER,MOD_TS,MOD_VERS,SELECTED_PROFILE_ID,IP_ADDRESS,GISPOSITION_ID, LIVEBROADCAST_ID) values ('302','FirstChannel-Novosibirsk','"Первый канал" - Новосибирск',null,null,'1','0',null,null,null,to_timestamp('19.10.12 10:06:53,778799000','DD.MM.RR HH24:MI:SS,FF'),'4',null,'192.168.115.52', '4979416', '5177808')
;
--Insert into AGENT_COPY (ID,NAME,DISPLAYNAME,DESCRIPTION,TIMEZONE,DIVISION_ID,DELETED,CREATION_DATE,CREATION_USER,MOD_USER,MOD_TS,MOD_VERS,SELECTED_PROFILE_ID,IP_ADDRESS,GISPOSITION_ID, LIVEBROADCAST_ID) values ('321','"Первый Канал"-Красноярск','"Первый Канал"-Красноярск',null,null,'1','0',null,null,null,to_timestamp('29.10.12 14:24:35,111136000','DD.MM.RR HH24:MI:SS,FF'),'1',null,null,null, null);
--Insert into AGENT_COPY (ID,NAME,DISPLAYNAME,DESCRIPTION,TIMEZONE,DIVISION_ID,DELETED,CREATION_DATE,CREATION_USER,MOD_USER,MOD_TS,MOD_VERS,SELECTED_PROFILE_ID,IP_ADDRESS,GISPOSITION_ID, LIVEBROADCAST_ID) values ('322','"Первый Канал"-Барнаул','"Первый Канал"-Барнаул',null,null,'1','0',null,null,null,to_timestamp('29.10.12 14:29:27,164301000','DD.MM.RR HH24:MI:SS,FF'),'1',null,null,null,null);
--Insert into AGENT_COPY (ID,NAME,DISPLAYNAME,DESCRIPTION,TIMEZONE,DIVISION_ID,DELETED,CREATION_DATE,CREATION_USER,MOD_USER,MOD_TS,MOD_VERS,SELECTED_PROFILE_ID,IP_ADDRESS,GISPOSITION_ID, LIVEBROADCAST_ID) values ('323','"Первый Канал"-Ростов на Дону','"Первый Канал"-Ростов на Дону',null,null,'1','0',null,null,null,to_timestamp('29.10.12 14:29:59,433608000','DD.MM.RR HH24:MI:SS,FF'),'1',null,null,null,null);
--Insert into AGENT_COPY (ID,NAME,DISPLAYNAME,DESCRIPTION,TIMEZONE,DIVISION_ID,DELETED,CREATION_DATE,CREATION_USER,MOD_USER,MOD_TS,MOD_VERS,SELECTED_PROFILE_ID,IP_ADDRESS,GISPOSITION_ID, LIVEBROADCAST_ID) values ('324','"Первый Канал"- Челябинск','"Первый Канал"- Челябинск',null,null,'1','0',null,null,null,to_timestamp('29.10.12 14:30:31,722592000','DD.MM.RR HH24:MI:SS,FF'),'1',null,null,null,null);
--Insert into AGENT_COPY (ID,NAME,DISPLAYNAME,DESCRIPTION,TIMEZONE,DIVISION_ID,DELETED,CREATION_DATE,CREATION_USER,MOD_USER,MOD_TS,MOD_VERS,SELECTED_PROFILE_ID,IP_ADDRESS,GISPOSITION_ID, LIVEBROADCAST_ID) values ('325','"Первый Канал" - Волгоград','"Первый Канал" - Волгоград',null,null,'1','0',null,null,null,to_timestamp('29.10.12 14:31:14,713607000','DD.MM.RR HH24:MI:SS,FF'),'1',null,null,null,null);
--Insert into AGENT_COPY (ID,NAME,DISPLAYNAME,DESCRIPTION,TIMEZONE,DIVISION_ID,DELETED,CREATION_DATE,CREATION_USER,MOD_USER,MOD_TS,MOD_VERS,SELECTED_PROFILE_ID,IP_ADDRESS,GISPOSITION_ID, LIVEBROADCAST_ID) values ('327','"Первый Канал" - Омск','"Первый Канал" - Омск',null,null,'1','0',null,null,null,to_timestamp('29.10.12 14:32:08,204663000','DD.MM.RR HH24:MI:SS,FF'),'1',null,null,null,null);
--Insert into AGENT_COPY (ID,NAME,DISPLAYNAME,DESCRIPTION,TIMEZONE,DIVISION_ID,DELETED,CREATION_DATE,CREATION_USER,MOD_USER,MOD_TS,MOD_VERS,SELECTED_PROFILE_ID,IP_ADDRESS,GISPOSITION_ID, LIVEBROADCAST_ID) values ('328','"Первый Канал" - Мурманск','"Первый Канал" - Мурманск',null,null,'1','0',null,null,null,to_timestamp('29.10.12 14:32:42,930892000','DD.MM.RR HH24:MI:SS,FF'),'1',null,null,null,null);
--Insert into AGENT_COPY (ID,NAME,DISPLAYNAME,DESCRIPTION,TIMEZONE,DIVISION_ID,DELETED,CREATION_DATE,CREATION_USER,MOD_USER,MOD_TS,MOD_VERS,SELECTED_PROFILE_ID,IP_ADDRESS,GISPOSITION_ID, LIVEBROADCAST_ID) values ('329','"Первый Канал" - Оренбург','"Первый Канал" - Оренбург',null,null,'1','0',null,null,null,to_timestamp('29.10.12 14:33:10,000849000','DD.MM.RR HH24:MI:SS,FF'),'1',null,null,null,null);
Insert into AGENT_COPY (ID,NAME,DISPLAYNAME,DESCRIPTION,TIMEZONE,DIVISION_ID,DELETED,CREATION_DATE,CREATION_USER,MOD_USER,MOD_TS,MOD_VERS,SELECTED_PROFILE_ID,IP_ADDRESS,GISPOSITION_ID, LIVEBROADCAST_ID) values ('282','FirstChannel-Yaroslavl','"Первый канал" - Ярославль',null,null,'1','0',null,null,null,to_timestamp('19.09.12 11:53:15,141821000','DD.MM.RR HH24:MI:SS,FF'),'2',null,'37.60.179.242','4979411', '5177805')
;
Insert into AGENT_COPY (ID,NAME,DISPLAYNAME,DESCRIPTION,TIMEZONE,DIVISION_ID,DELETED,CREATION_DATE,CREATION_USER,MOD_USER,MOD_TS,MOD_VERS,SELECTED_PROFILE_ID,IP_ADDRESS,GISPOSITION_ID, LIVEBROADCAST_ID) values ('283','FirstChannel-Perm','"Первый канал" - Пермь',null,null,'1','0',null,null,null,to_timestamp('19.09.12 11:53:15,140778000','DD.MM.RR HH24:MI:SS,FF'),'1',null,'195.69.158.68','4979410', '5177806')
;
--Insert into AGENT_COPY (ID,NAME,DISPLAYNAME,DESCRIPTION,TIMEZONE,DIVISION_ID,DELETED,CREATION_DATE,CREATION_USER,MOD_USER,MOD_TS,MOD_VERS,SELECTED_PROFILE_ID,IP_ADDRESS,GISPOSITION_ID, LIVEBROADCAST_ID) values ('284','РЧЦ','РЧЦ',null,null,'1','284',null,null,null,to_timestamp('19.09.12 13:12:43,973286000','DD.MM.RR HH24:MI:SS,FF'),'2',null,null,null,null);
Insert into AGENT_COPY (ID,NAME,DISPLAYNAME,DESCRIPTION,TIMEZONE,DIVISION_ID,DELETED,CREATION_DATE,CREATION_USER,MOD_USER,MOD_TS,MOD_VERS,SELECTED_PROFILE_ID,IP_ADDRESS,GISPOSITION_ID, LIVEBROADCAST_ID) values ('286','FirstChannel-Kazan','"Первый канал" - Казань',null,null,'1','0',null,null,null,to_timestamp('23.10.12 12:52:03,161235000','DD.MM.RR HH24:MI:SS,FF'),'10','123','31.13.131.14', '4979409', '5177807')
;
Insert into AGENT_COPY (ID,NAME,DISPLAYNAME,DESCRIPTION,TIMEZONE,DIVISION_ID,DELETED,CREATION_DATE,CREATION_USER,MOD_USER,MOD_TS,MOD_VERS,SELECTED_PROFILE_ID,IP_ADDRESS,GISPOSITION_ID, LIVEBROADCAST_ID) values ('303','FirstChannel-SPB','"Первый канал"- Санкт-Петербург',null,null,'1','0',null,null,null,to_timestamp('26.10.12 14:03:32,729623000','DD.MM.RR HH24:MI:SS,FF'),'7',null,'31.28.9.230','4979412','5177809')
;