DROP TABLE MAGENTMODULE
;

  CREATE TABLE "MAGENTMODULE" (
  "ID" NUMBER(10,0),
  "TEMPLATERESULTCONFIGURATION_ID" NUMBER(10,0),
  "DISPLAYNAME" VARCHAR2(100), 
  "RESULTTYPE" VARCHAR2(100), 
  "NAME" VARCHAR2(100))
  ;
 
Insert into MAGENTMODULE (ID,TEMPLATERESULTCONFIGURATION_ID,DISPLAYNAME,RESULTTYPE,NAME) values ('4','1','Качество аналогового сигнала - IT-09A','MTvIt09aResult','IT09AControlModule')
;
Insert into MAGENTMODULE (ID,TEMPLATERESULTCONFIGURATION_ID,DISPLAYNAME,RESULTTYPE,NAME) values ('7',null,'TV Stream Monitor','MTvStreamResult','TVStreamControlModule')
;
Insert into MAGENTMODULE (ID,TEMPLATERESULTCONFIGURATION_ID,DISPLAYNAME,RESULTTYPE,NAME) values ('261',null,'Телерадиовещание','MTvResult','SignalLevelControlModule')
;