DROP TABLE MEVENT
;
CREATE TABLE "MEVENT" (
	"ID" NUMBER (10,0), 
	"TYPE" VARCHAR2 (256),
	"OWNER" VARCHAR2 (256),
	"VALUE" VARCHAR2 (400),
	"CREATEDDATETIME" DATE,
	CONSTRAINT "MEVENT" PRIMARY KEY ("ID")
)
;