DROP TABLE MRESULTCONFIGU_MRESULTPARAMET
;
CREATE TABLE "MRESULTCONFIGU_MRESULTPARAMET"
  (
    "MRESULTCONFIGURATION_ID"    NUMBER(19,0) NOT NULL ENABLE,
    "PARAMETERCONFIGURATIONS_ID" NUMBER(19,0) NOT NULL ENABLE,
    UNIQUE ("PARAMETERCONFIGURATIONS_ID") ENABLE,
    FOREIGN KEY ("MRESULTCONFIGURATION_ID") REFERENCES "MRESULTCONFIGURATION" ("ID") ENABLE,
    FOREIGN KEY ("PARAMETERCONFIGURATIONS_ID") REFERENCES "MRESULTPARAMETERCONFIGURATION" ("ID") ENABLE
  )
;
Insert into MRESULTCONFIGU_MRESULTPARAMET (MRESULTCONFIGURATION_ID,PARAMETERCONFIGURATIONS_ID) values ('1','1')
;
Insert into MRESULTCONFIGU_MRESULTPARAMET (MRESULTCONFIGURATION_ID,PARAMETERCONFIGURATIONS_ID) values ('1','2')
;
Insert into MRESULTCONFIGU_MRESULTPARAMET (MRESULTCONFIGURATION_ID,PARAMETERCONFIGURATIONS_ID) values ('1','3')
;
