DROP TABLE MPARAMETERTHRESHOLD
;
CREATE TABLE "MPARAMETERTHRESHOLD"
  (
    "ID" NUMBER(19,0) NOT NULL ENABLE,
    "CRITICALVALUE" FLOAT(126),
    "TYPE" VARCHAR2(64 BYTE),
    "WARNINGVALUE" FLOAT(126),
    PRIMARY KEY ("ID") ENABLE
  )
;
Insert into MPARAMETERTHRESHOLD (ID,CRITICALVALUE,TYPE,WARNINGVALUE) values ('1','50','LESS','60')
;
Insert into MPARAMETERTHRESHOLD (ID,CRITICALVALUE,TYPE,WARNINGVALUE) values ('2','50','LESS','60')
;
Insert into MPARAMETERTHRESHOLD (ID,CRITICALVALUE,TYPE,WARNINGVALUE) values ('3','13','LESS','13')
;
