DROP TABLE MRESULTPARAMETERCONFIGURATION
;
CREATE TABLE "MRESULTPARAMETERCONFIGURATION"
  (
    "ID"                    NUMBER(19,0) NOT NULL ENABLE,
    "AGGREGATIONTYPE"       VARCHAR2(255 CHAR),
    "DISPLAYNAME"  VARCHAR2(255 CHAR),
    "DESCRIPTION"  VARCHAR2(255 CHAR),
    "NAME"         VARCHAR2(255 CHAR),
    "THRESHOLD_ID" NUMBER(19,0),
    "LOCATION_ID"  NUMBER(19,0),
    PRIMARY KEY ("ID") ENABLE,
    FOREIGN KEY ("THRESHOLD_ID") REFERENCES "MPARAMETERTHRESHOLD" ("ID") ENABLE,
    FOREIGN KEY ("LOCATION_ID")  REFERENCES "MRESULTPARAMETERLOCATION" ("ID") ENABLE
  )
; 
Insert into MRESULTPARAMETERCONFIGURATION (ID,AGGREGATIONTYPE,DISPLAYNAME,DESCRIPTION,NAME,THRESHOLD_ID,LOCATION_ID) values ('1','MIN','Уровень сигнала','Уровень сигнала (дБ/мкв)','signalLevel','1',null)
;
Insert into MRESULTPARAMETERCONFIGURATION (ID,AGGREGATIONTYPE,DISPLAYNAME,DESCRIPTION,NAME,THRESHOLD_ID,LOCATION_ID) values ('2','MIN','Отношение сигнал/шум','Отношение сигнал/шум (дБ)','signalNoise','2',null)
;
Insert into MRESULTPARAMETERCONFIGURATION (ID,AGGREGATIONTYPE,DISPLAYNAME,DESCRIPTION,NAME,THRESHOLD_ID,LOCATION_ID) values ('3','MIN','Отношение уровень видео/уровень аудио','Отношение уровень видео/уровень аудио (дБ)','videoAudio','3',null)
;

