CREATE TABLE "MRESULTPARAMETERLOCATION"
(
    "ID"           NUMBER(19,0) NOT NULL ENABLE,
    "FILELOCATION" VARCHAR2(255 CHAR),
    "FILENAME"     VARCHAR2(255 CHAR),
    PRIMARY KEY ("ID") ENABLE
)
;
