DROP TABLE MRESULTCONFIGURATION
;
CREATE TABLE "MRESULTCONFIGURATION"
  (
    "ID"                             NUMBER(19,0) NOT NULL ENABLE,
    "SAMPLINGRATE"                   NUMBER(19,0),
    "TEMPLATERESULTCONFIGURATION_ID" NUMBER(19,0),
    PRIMARY KEY ("ID") ENABLE,
    FOREIGN KEY ("TEMPLATERESULTCONFIGURATION_ID") REFERENCES "MRESULTCONFIGURATION" ("ID") ENABLE
  )
;
Insert into MRESULTCONFIGURATION (ID,SAMPLINGRATE,TEMPLATERESULTCONFIGURATION_ID) values ('1','1',null)
;
