---
- name: check if ports is redirected
  shell: iptables -L -t nat | grep 'Redirect {{ item.protocol }}:{{ item.dport }}->{{ item.toport }}'
  with_items: redirect_ports
  register: redirect_checks
  ignore_errors: yes
  changed_when: no
  when: redirect_ports is defined

- name: redirect ports incoming
  shell: iptables -t nat -I PREROUTING -p "{{ item.item.protocol }}" --dport "{{ item.item.dport }}" -j REDIRECT --to-ports "{{ item.item.toport }}"  -m comment --comment "Redirect {{ item.item.protocol }}:{{ item.item.dport }}->{{ item.item.toport }}"
  when: redirect_checks.results is defined and item.rc != 0
  with_items: redirect_checks.results
  notify: save iptables

- name: check if local ports is redirected
  shell: iptables -L -t nat | grep 'Redirect local {{ item.protocol }}:{{ item.dport }}->{{ item.toport }}'
  with_items: redirect_ports
  register: redirect_checks_local
  ignore_errors: yes
  changed_when: no
  when: redirect_ports is defined

- name: redirect ports local
  shell: iptables -t nat -I OUTPUT -o lo -p "{{ item.item.protocol }}" --dport "{{ item.item.dport }}" -j REDIRECT --to-ports "{{ item.item.toport }}"  -m comment --comment "Redirect local {{ item.item.protocol }}:{{ item.item.dport }}->{{ item.item.toport }}"
  when: redirect_checks_local.results is defined and item.rc != 0
  with_items: redirect_checks_local.results
  notify: save iptables
