---
- stat: path={{ consul_home }}/dist
  register: dist_stat

- name: copy and unpack ui
  unarchive: >
    src={{ consul_ui_archive }}
    dest={{ consul_home }}
    owner={{ consul_user }}
    group={{ consul_group }}
  when: not dist_stat.stat.exists
