---
- name: Install rabbit
  yum: name=rabbitmq-server disablerepo=* enablerepo=localrepo state=installed

- name: Copy config
  template: >
    src=rabbitmq.config.j2
    dest=/etc/rabbitmq/rabbitmq.config
  notify: restart rabbit

- name: Create cookie
  template: >
    src=erlang.cookie.j2
    dest=/var/lib/rabbitmq/.erlang.cookie
    owner=rabbitmq
    group=rabbitmq
    mode=600
  notify: restart rabbit
  when: rabbit_is_cluster

- name: Check menagement plugins
  command: grep -q rabbitmq_management /etc/rabbitmq/enabled_plugins
  register: rabbit_mgmt_plugin
  changed_when: no
  ignore_errors: yes

- name: Add management plugin
  command: rabbitmq-plugins enable rabbitmq_management
  when: rabbit_mgmt_plugin | failed

- name: Start rabbit
  service: name=rabbitmq-server state=started enabled=yes
